version: "3.8"
services:
    cassandra-seed:
        image: cassandra:3.11.7
        networks:
            - cassandra-net
        environment:
            - CASSANDRA_BROADCAST_ADDRESS=cassandra-seed
            - CASSANDRA_CLUSTER_NAME=my-cluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=my-datacenter-1
            - CASSANDRA_RACK=rack1
        volumes:
            - /home/picocluster64/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
            - data_cassandra_1:/var/lib/cassandra
        deploy:
            placement:
                constraints:
                    - node.hostname == pc0  # The seed node is running on pc0
    cassandra-node:
        image: cassandra:3.11.7
        networks:
            - cassandra-net
        environment:
            - CASSANDRA_SEEDS=cassandra-seed
            - CASSANDRA_CLUSTER_NAME=my-cluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=my-datacenter-1
            - CASSANDRA_RACK=rack1
        volumes:
            - /home/picocluster64/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
            - data_cassandra_2:/var/lib/cassandra
        deploy:
            mode: global  # Ensure one replica runs on every available node
        depends_on:
            - cassandra-seed
networks:
    cassandra-net:
        driver: overlay

volumes:
  data_cassandra_1:
  data_cassandra_2:
