version: '3.8'

networks:
  cassandra:
    external: true

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    hostname: cassandra1
    networks:
      - cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6,cassandra7,cassandra8,cassandra9"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    volumes:
      - cassandra-config1:/etc/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    hostname: cassandra2
    networks:
      - cassandra
    ports:
      - "9043:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6,cassandra7,cassandra8,cassandra9"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    depends_on:
      - cassandra1
    volumes:
      - cassandra-config2:/etc/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    hostname: cassandra3
    networks:
      - cassandra
    ports:
      - "9044:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6,cassandra7,cassandra8,cassandra9"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    depends_on:
      - cassandra2
    volumes:
      - cassandra-config3:/etc/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

  cassandra4:
    image: cassandra:latest
    container_name: cassandra4
    hostname: cassandra4
    networks:
      - cassandra
    ports:
      - "9045:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6,cassandra7,cassandra8,cassandra9"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    depends_on:
      - cassandra3
    volumes:
      - cassandra-config4:/etc/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

  cassandra5:
    image: cassandra:latest
    container_name: cassandra5
    hostname: cassandra5
    networks:
      - cassandra
    ports:
      - "9046:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6,cassandra7,cassandra8,cassandra9"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    depends_on:
      - cassandra4
    volumes:
      - cassandra-config5:/etc/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

  cassandra6:
    image: cassandra:latest
    container_name: cassandra6
    hostname: cassandra6
    networks:
      - cassandra
    ports:
      - "9047:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6,cassandra7,cassandra8,cassandra9"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    depends_on:
      - cassandra5
    volumes:
      - cassandra-config6:/etc/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

  cassandra7:
    image: cassandra:latest
    container_name: cassandra7
    hostname: cassandra7
    networks:
      - cassandra
    ports:
      - "9048:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6,cassandra7,cassandra8,cassandra9"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    depends_on:
      - cassandra6
    volumes:
      - cassandra-config7:/etc/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

  cassandra8:
    image: cassandra:latest
    container_name: cassandra8
    hostname: cassandra8
    networks:
      - cassandra
    ports:
      - "9049:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6,cassandra7,cassandra8,cassandra9"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    depends_on:
      - cassandra7
    volumes:
      - cassandra-config8:/etc/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

  cassandra9:
    image: cassandra:latest
    container_name: cassandra9
    hostname: cassandra9
    networks:
      - cassandra
    ports:
      - "9050:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6,cassandra7,cassandra8,cassandra9"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    depends_on:
      - cassandra8
    volumes:
      - cassandra-config9:/etc/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  cassandra-config1:
  cassandra-config2:
  cassandra-config3:
  cassandra-config4:
  cassandra-config5:
  cassandra-config6:
  cassandra-config7:
  cassandra-config8:
  cassandra-config9:
