version: "3.8"
services:
    cassandra-seed:
        image: cassandra:3.11.7
        networks:
            - cassandra-net
        environment:
            - CASSANDRA_BROADCAST_ADDRESS=cassandra-seed
        deploy:
            placement:
                constraints:
                    - node.hostname == pc0  # The seed node is running on pc0
    cassandra-node:
        image: cassandra:3.11.7
        networks:
            - cassandra-net
        environment:
            - CASSANDRA_SEEDS=cassandra-seed
        deploy:
            mode: global  # Ensure one replica runs on every available node
        depends_on:
            - cassandra-seed
networks:
    cassandra-net:
        driver: overlay
